Traceback (most recent call last):
  File "./RayTracerMainProgram.py", line 849, in <module>
    main(sys.argv)
  File "./RayTracerMainProgram.py", line 803, in main
    Grid,G_z,timep=power_grid(Sheetname,Room,repeat,plottype,Roomnum,job)  # Use the ray information to compute the power
  File "./RayTracerMainProgram.py", line 545, in power_grid
    Mesh= DSM.load_dict(meshname)
  File "/beegfs/scratch/user/m/hw454/Raytracer/ParameterIndependent/DictionarySparseMatrix.py", line 2450, in load_dict
    with open(filename_, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './Mesh/MultiRefBoxCorner/DSM022Refs002_tx000.npy'

real	0m4.602s
user	0m3.919s
sys	0m0.093s
Traceback (most recent call last):
  File "./RayTracerMainProgram.py", line 849, in <module>
    main(sys.argv)
  File "./RayTracerMainProgram.py", line 803, in main
    Grid,G_z,timep=power_grid(Sheetname,Room,repeat,plottype,Roomnum,job)  # Use the ray information to compute the power
  File "./RayTracerMainProgram.py", line 545, in power_grid
    Mesh= DSM.load_dict(meshname)
  File "/beegfs/scratch/user/m/hw454/Raytracer/ParameterIndependent/DictionarySparseMatrix.py", line 2450, in load_dict
    with open(filename_, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './Mesh/MultiRefBoxCorner/DSM022Refs002_tx001.npy'

real	0m4.387s
user	0m3.934s
sys	0m0.086s

real	4m51.069s
user	4m50.009s
sys	0m0.091s

real	5m5.623s
user	5m4.835s
sys	0m0.100s

real	4m56.584s
user	4m56.106s
sys	0m0.087s

real	5m8.178s
user	5m7.817s
sys	0m0.097s

real	5m15.949s
user	5m15.478s
sys	0m0.101s

real	5m25.370s
user	5m24.571s
sys	0m0.093s

real	5m30.064s
user	5m29.453s
sys	0m0.103s

real	5m42.138s
user	5m40.111s
sys	0m0.097s
Traceback (most recent call last):
  File "./RayTracerMainProgram.py", line 849, in <module>
    main(sys.argv)
  File "./RayTracerMainProgram.py", line 803, in main
    Grid,G_z,timep=power_grid(Sheetname,Room,repeat,plottype,Roomnum,job)  # Use the ray information to compute the power
  File "./RayTracerMainProgram.py", line 545, in power_grid
    Mesh= DSM.load_dict(meshname)
  File "/beegfs/scratch/user/m/hw454/Raytracer/ParameterIndependent/DictionarySparseMatrix.py", line 2450, in load_dict
    with open(filename_, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './Mesh/MultiRefBoxCorner/DSM022Refs002_tx010.npy'

real	0m4.999s
user	0m3.954s
sys	0m0.093s
Traceback (most recent call last):
  File "./RayTracerMainProgram.py", line 849, in <module>
    main(sys.argv)
  File "./RayTracerMainProgram.py", line 803, in main
    Grid,G_z,timep=power_grid(Sheetname,Room,repeat,plottype,Roomnum,job)  # Use the ray information to compute the power
  File "./RayTracerMainProgram.py", line 545, in power_grid
    Mesh= DSM.load_dict(meshname)
  File "/beegfs/scratch/user/m/hw454/Raytracer/ParameterIndependent/DictionarySparseMatrix.py", line 2450, in load_dict
    with open(filename_, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './Mesh/MultiRefBoxCorner/DSM022Refs002_tx011.npy'

real	0m4.477s
user	0m3.924s
sys	0m0.074s

real	5m10.041s
user	5m9.633s
sys	0m0.085s

real	5m16.320s
user	5m15.062s
sys	0m0.103s

real	5m13.565s
user	5m10.242s
sys	0m0.100s

real	5m23.244s
user	5m20.270s
sys	0m0.107s

real	5m29.961s
user	5m28.554s
sys	0m0.096s

real	5m34.307s
user	5m32.887s
sys	0m0.085s

real	5m42.494s
user	5m41.761s
sys	0m0.084s

real	5m56.015s
user	5m55.319s
sys	0m0.104s

real	6m37.534s
user	6m36.702s
sys	0m0.114s

real	6m40.754s
user	6m40.177s
sys	0m0.093s

real	6m37.884s
user	6m37.162s
sys	0m0.102s

real	6m33.211s
user	6m32.191s
sys	0m0.115s

real	6m31.246s
user	6m29.512s
sys	0m0.114s

real	6m27.888s
user	6m26.958s
sys	0m0.095s

real	6m36.463s
user	6m35.653s
sys	0m0.102s

real	6m44.785s
user	6m43.548s
sys	0m0.096s

real	6m47.247s
user	6m45.966s
sys	0m0.098s

real	6m46.515s
user	6m44.905s
sys	0m0.099s

real	6m55.250s
user	6m54.268s
sys	0m0.112s

real	6m55.109s
user	6m54.272s
sys	0m0.093s

real	6m54.793s
user	6m53.370s
sys	0m0.111s

real	6m38.858s
user	6m37.758s
sys	0m0.108s

real	6m41.618s
user	6m40.319s
sys	0m0.097s

real	6m48.863s
user	6m48.332s
sys	0m0.100s

real	6m47.480s
user	6m46.967s
sys	0m0.088s

real	6m52.986s
user	6m50.946s
sys	0m0.083s

real	6m57.235s
user	6m56.048s
sys	0m0.082s

real	7m0.922s
user	6m57.762s
sys	0m0.104s

real	4m41.777s
user	4m39.484s
sys	0m0.102s

real	4m38.109s
user	4m37.427s
sys	0m0.100s

real	4m47.442s
user	4m47.020s
sys	0m0.103s

real	4m49.751s
user	4m49.225s
sys	0m0.092s

real	4m59.120s
user	4m58.252s
sys	0m0.114s

real	6m38.634s
user	6m38.051s
sys	0m0.088s

real	6m40.536s
user	6m39.942s
sys	0m0.079s

real	6m42.437s
user	6m41.506s
sys	0m0.107s

real	6m45.035s
user	6m44.569s
sys	0m0.112s

real	6m47.453s
user	6m47.136s
sys	0m0.083s
Traceback (most recent call last):
  File "./RayTracerMainProgram.py", line 849, in <module>
    main(sys.argv)
  File "./RayTracerMainProgram.py", line 803, in main
    Grid,G_z,timep=power_grid(Sheetname,Room,repeat,plottype,Roomnum,job)  # Use the ray information to compute the power
  File "./RayTracerMainProgram.py", line 545, in power_grid
    Mesh= DSM.load_dict(meshname)
  File "/beegfs/scratch/user/m/hw454/Raytracer/ParameterIndependent/DictionarySparseMatrix.py", line 2450, in load_dict
    with open(filename_, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './Mesh/MultiRefBoxCorner/DSM022Refs002_tx050.npy'

real	0m4.654s
user	0m3.921s
sys	0m0.096s
Traceback (most recent call last):
  File "./RayTracerMainProgram.py", line 849, in <module>
    main(sys.argv)
  File "./RayTracerMainProgram.py", line 803, in main
    Grid,G_z,timep=power_grid(Sheetname,Room,repeat,plottype,Roomnum,job)  # Use the ray information to compute the power
  File "./RayTracerMainProgram.py", line 545, in power_grid
    Mesh= DSM.load_dict(meshname)
  File "/beegfs/scratch/user/m/hw454/Raytracer/ParameterIndependent/DictionarySparseMatrix.py", line 2450, in load_dict
    with open(filename_, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './Mesh/MultiRefBoxCorner/DSM022Refs002_tx051.npy'

real	0m4.116s
user	0m3.922s
sys	0m0.086s

real	5m3.398s
user	5m3.199s
sys	0m0.086s

real	5m8.421s
user	5m7.954s
sys	0m0.106s

real	5m12.669s
user	5m12.328s
sys	0m0.073s

real	5m21.275s
user	5m20.865s
sys	0m0.100s

real	5m29.796s
user	5m29.335s
sys	0m0.120s

real	5m40.332s
user	5m40.035s
sys	0m0.108s

real	5m44.408s
user	5m44.012s
sys	0m0.096s

real	5m56.832s
user	5m56.467s
sys	0m0.106s
Traceback (most recent call last):
  File "./RayTracerMainProgram.py", line 849, in <module>
    main(sys.argv)
  File "./RayTracerMainProgram.py", line 803, in main
    Grid,G_z,timep=power_grid(Sheetname,Room,repeat,plottype,Roomnum,job)  # Use the ray information to compute the power
  File "./RayTracerMainProgram.py", line 545, in power_grid
    Mesh= DSM.load_dict(meshname)
  File "/beegfs/scratch/user/m/hw454/Raytracer/ParameterIndependent/DictionarySparseMatrix.py", line 2450, in load_dict
    with open(filename_, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './Mesh/MultiRefBoxCorner/DSM022Refs002_tx060.npy'

real	0m4.281s
user	0m3.933s
sys	0m0.098s
Traceback (most recent call last):
  File "./RayTracerMainProgram.py", line 849, in <module>
    main(sys.argv)
  File "./RayTracerMainProgram.py", line 803, in main
    Grid,G_z,timep=power_grid(Sheetname,Room,repeat,plottype,Roomnum,job)  # Use the ray information to compute the power
  File "./RayTracerMainProgram.py", line 545, in power_grid
    Mesh= DSM.load_dict(meshname)
  File "/beegfs/scratch/user/m/hw454/Raytracer/ParameterIndependent/DictionarySparseMatrix.py", line 2450, in load_dict
    with open(filename_, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './Mesh/MultiRefBoxCorner/DSM022Refs002_tx061.npy'

real	0m4.111s
user	0m3.917s
sys	0m0.080s

real	5m23.861s
user	5m23.640s
sys	0m0.086s

real	5m28.177s
user	5m27.726s
sys	0m0.100s

real	5m23.238s
user	5m22.883s
sys	0m0.077s

real	5m35.250s
user	5m34.933s
sys	0m0.106s

real	5m44.134s
user	5m43.790s
sys	0m0.097s

real	5m49.059s
user	5m48.592s
sys	0m0.106s
slurmstepd: error: *** JOB 3466490 ON node-sw-104 CANCELLED AT 2020-11-23T01:13:06 DUE TO TIME LIMIT ***
